spring.application.name=user-service
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5435/user_service
spring.datasource.username=kartlyuser
spring.datasource.password=user123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

jwt.secret=4f8b9e2c1a3d5f6e7b8a9c0f1e2d3c4b5a6f7e8d9c0b1a2f3e4d5c6b7a8f9e01
jwt.expiration-ms=3600000