spring.application.name=user-service
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5435/user_service
spring.datasource.username=kartlyuser
spring.datasource.password=user123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

jwt.secret=4f8b9e2c1a3d5f6e7b8a9c0f1e2d3c4b5a6f7e8d9c0b1a2f3e4d5c6b7a8f9e01
jwt.expiration-ms=3600000

spring.security.oauth2.client.registration.auth0.client-id=xGs7c2xRvYRkVUYOuk5mkwgswXtPF9dQ
spring.security.oauth2.client.registration.auth0.client-secret=${AUTH0_CLIENT_SECRET:not-set}
spring.security.oauth2.client.registration.auth0.scope=openid,email,profile
spring.security.oauth2.client.registration.auth0.redirect-uri=http://localhost:8080/login/oauth2/code/auth0
spring.security.oauth2.client.provider.auth0.issuer-uri=https://kartly.ca.auth0.com/